### PR TITLE
Java 21 & 20 support

### PR DESCRIPTION
**Pull request by spangaer**
Self explanatory.

### CODE REVIEW

**Comment by mkurz** [comment]
Tests fail

**Comment by spangaer** [comment]
🤦‍♂️ so much for a 5-minute fix.
I'll look in to that.

**Comment by spangaer** [comment]
GitHub VSCode had me fooled 🤷‍♂️

**Comment by mkurz** [comment]
Pushed v6.2.0, should be on Maven Central in like 30 minutes:
- https://github.com/sbt/sbt-eclipse/actions/runs/7222389745
- https://repo1.maven.org/maven2/com/github/sbt/sbt-eclipse_2.12_1.0/6.2.0/

**Pull request merged**
